<?php

class Codex_Xtest_Xtest_Unit_Admin extends Codex_Xtest_Xtest_Unit_Abstract
{
    protected function setUp()
    {
        parent::setUp();
        Xtest::initAdmin();
    }

    public function dispatch($route, $params = array())
    {
        Mage::app()->getStore()->setConfig("admin/security/use_form_key", 0);

        /*
        $mock = $this->getModelMock('admin/session', array('isLoggedIn','getUser') );
        $mock->expects( $this->any() )
            ->method('isLoggedIn')
            ->willReturn( $this->returnValue( true ) );

        $mock->expects( $this->any() )
            ->method('getUser')
            ->willReturn( Mage::getModel('admin/user') );

        $this->addModelMock('admin/session', $mock);
        */

        $adminusers = Mage::getModel('admin/user')->getCollection()
            ->addFieldToFilter('username', array( 'like' => '%-cxus'));

        if ($adminusers->getSize() >= 1) {
            $adminuser = $adminusers->getFirstItem();
            $adminsession = Mage::getSingleton('admin/session');
            $adminsession->setUser($adminuser);
            $adminsession->setAcl(Mage::getResourceModel('admin/acl')->loadAcl());
        }

        // TODO: Über ein Mock lösen!

        parent::dispatch($route, $params); // TODO: Change the autogenerated stub
    }

}